const Images = [
  {image: require('../assets/food5.jpg')},
  {image: require('../assets/food2.jpg')},
  {image: require('../assets/food5.jpg')},
  {image: require('../assets/food2.jpg')},
  {image: require('../assets/food5.jpg')},
];

export const data = [
  {
    id: '1',
    coordinate: {
      latitude: 22.6293867,
      longitude: 88.4354486,
    },
    title: `Break Fast`,
    deliveryTime: `delivery time`,
    description: `dessert`,
    image: Images[0].image,
    rating: 4,
    reviews: 99,
    time: `45 min`,
    categories: ['Restaurant', 'Hotel', 'Dineout'],
  },
  {
    id: '2',
    coordinate: {
      latitude: 22.6345648,
      longitude: 88.4377279,
    },
    title: 'Lunch',
    deliveryTime: `delivery time`,
    description: `dessert`,
    image: Images[1].image,
    rating: 5,
    reviews: 102,
    time: `45 min`,
    categories: ['Restaurant', 'Fastfood Center', 'Snacks Corner'],
  },
  {
    id: '3',
    coordinate: {
      latitude: 22.6281662,
      longitude: 88.4410113,
    },
    title: 'Dinner',
    deliveryTime: `delivery time`,
    description: `dessert`,
    image: Images[2].image,
    rating: 3,
    reviews: 220,
    time: `45 min`,
    categories: ['Restaurant', 'Hotel', 'Dineout'],
  },
  {
    id: '4',
    coordinate: {
      latitude: 22.6341137,
      longitude: 88.4497463,
    },
    title: 'Veg',
    deliveryTime: `delivery time`,
    description: `dessert`,
    image: Images[3].image,
    rating: 4,
    reviews: 48,
    time: `45 min`,
    categories: ['Restaurant', 'Fastfood Center', 'Snacks Corner'],
  },
  {
    id: '5',
    coordinate: {
      latitude: 22.6292757,
      longitude: 88.444781,
    },
    title: 'Non Veg',
    description: `dessert`,
    deliveryTime: `delivery time`,
    image: Images[4].image,
    rating: 4,
    reviews: 178,
    time: `45 min`,
    categories: ['Restaurant', 'Hotel', 'Dineout'],
  },
  {
    id: '6',
    coordinate: {
      latitude: 22.6293867,
      longitude: 88.4354486,
    },
    title: 'Sea Food',
    description: `dessert`,
    deliveryTime: `delivery time`,
    image: Images[0].image,
    rating: 4,
    reviews: 99,
    time: `45 min`,
    categories: ['Restaurant', 'Hotel', 'Dineout'],
  },
  {
    id: '7',
    coordinate: {
      latitude: 22.6345648,
      longitude: 88.4377279,
    },
    title: 'Lunch',
    deliveryTime: `delivery time`,
    description: `dessert`,
    image: Images[1].image,
    rating: 5,
    reviews: 102,
    time: `45 min`,
    categories: ['Restaurant', 'Fastfood Center', 'Snacks Corner'],
  },
];
//ddd